name: 'Cache cargo'
description: 'Cache cargo'

inputs:
  key:
    description: 'Cache key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ inputs.key }}
