name: "Build Nix package on Ubuntu"

on:
  push:

jobs:
  build_legacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Building package
        run: nix-build . -A defaultPackage.x86_64-linux
  build_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Building package
        run: nix build
