name: Publish Rust crate

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: rustup update --no-self-update stable && rustup default stable

      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_API_KEY }}"
